[package]
name = "screen-ball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12"
bevy_xpbd_3d = "0.3.1"
# TODO 可以使用winit获取
display-info = "0.4.1"