[package]
name = "screen-ball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"
bevy_rapier3d = "0.21"
# TODO 可以使用winit获取
display-info = "0.3.2"